version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://fooddelivery:password@postgres:5432/fooddelivery?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key
      - ENVIRONMENT=development
      - STRIPE_KEY=sk_test_dummy
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - food-delivery-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=fooddelivery
      - POSTGRES_USER=fooddelivery
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - food-delivery-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - food-delivery-network

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - food-delivery-network

volumes:
  postgres_data:
  redis_data:

networks:
  food-delivery-network:
    driver: bridge

