services:
  - type: web
    name: food-delivery-api
    env: go
    buildCommand: go build -o main cmd/main.go
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: food-delivery-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: food-delivery-redis
          property: connectionString

databases:
  - name: food-delivery-db
    databaseName: fooddelivery
    user: fooddelivery

services:
  - type: redis
    name: food-delivery-redis
    maxmemoryPolicy: allkeys-lru

