services:
  - type: web
    name: food-delivery-api
    env: go
    plan: free
    buildCommand: go build -o food-delivery cmd/main.go
    startCommand: ./food-delivery
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://madhavinternship2024:GDuUTED803LIihgx@cluster0.zpn8u9a.mongodb.net/food?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
    healthCheckPath: /health
    autoDeploy: true



services:
  - type: redis
    name: food-delivery-redis
    maxmemoryPolicy: allkeys-lru

