services:
  - type: web
    name: food-delivery-backend
    runtime: go
    buildCommand: go build -o bin/main cmd/main.go
    startCommand: ./bin/main
    plan: starter
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
      - key: GO_VERSION
        value: "1.21"
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: food-delivery-postgres
    databaseName: food_delivery
    user: postgres
    plan: starter

  - name: food-delivery-redis
    type: redis
    plan: starter
